apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestione-spazi-domain
  namespace: gestione-spazi
  labels:
    app: gestione-spazi-domain
spec:
  replicas: 1
  selector:
    matchLabels:
    
      app: gestione-spazi-domain
  template:
    metadata:
      labels:
        app: gestione-spazi-domain
    spec:
      containers:
      - name: gestione-spazi-domain
        image: # da definire        
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            requests:
                memory: "250Mi"
                cpu: "100m"
            limits:
                memory: "500Mi"
                cpu: "500m"
        livenessProbe:
            tcpSocket:
                port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
                name: database-config
                key: DB_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
                name: mysql-secret
                key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mysql-secret
                key: password